### ISSUE TITLE
Can't determine type for tag '<macro name="m3_comp_bottom_app_bar_container_color">?attr/colorSurface</macro>'

### ISSUE THREAD

**Issue by gancao297871092** [walterholohan/react-native-crisp-chat-sdk#112]
Can't determine type for tag '<macro name="m3_comp_bottom_app_bar_container_color">?attr/colorSurface</macro>'

**Comment by malik-korucu** [comment]
it's same here

**Comment by baptistejamin** [comment]
What build target are you using for Android?

**Comment by malik-korucu** [comment]
@baptistejamin 

buildscript {
    ext {
        buildToolsVersion = "30.0.2"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 33
        kotlinVersion = "1.6.21"
        googlePlayServicesAuthVersion = "19.2.0"
    }
    repositories {
        mavenCentral()
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.2.1'
        classpath 'com.google.gms:google-services:4.3.10'
        classpath("com.google.firebase:firebase-crashlytics-gradle:2.0.0")
    }
}

**Comment by baptistejamin** [comment]
Hey there.

The SDK got updated with latest react native. It should work now
