### ISSUE TITLE
pushSessionEvent is not a function iOS

### ISSUE THREAD

**Issue by MichaelHuy** [walterholohan/react-native-crisp-chat-sdk#12]
Hi all,
I got this error when using pushSessionEvent on iOS

TypeError: _reactNativeCrispChatSdk.default.pushSessionEvent is not a function. (In '_reactNativeCrispChatSdk.default.pushSessionEvent("Login", _reactNativeCrispChatSdk.CrispSessionEventColors.blue)', '_reactNativeCrispChatSdk.default.pushSessionEvent' is undefined)

Any advice? Thanks

**Comment by MichaelHuy** [comment]
I follow the Readme file CrispChatSDK.pushSessionEvent(name: "Signup", color: CrispSessionEventColors.blue) (iOS only)
, But it shows the same error above

**Comment by walterholohan** [comment]
Hey @MichaelHuy , thank you for raising this issue. I have just pushed a fix for this. It can be found in `0.5.0` (https://github.com/walterholohan/react-native-crisp-chat-sdk/releases/tag/v0.5.0)

**Comment by walterholohan** [comment]
Closing issue. Fix can found here https://github.com/walterholohan/react-native-crisp-chat-sdk/releases/tag/v0.5.0
