### ISSUE TITLE
Android chat modal will overflow when keyboard present

### ISSUE THREAD

**Issue by clspeter** [walterholohan/react-native-crisp-chat-sdk#129]
Hi All
Please see attached video file for behavior

Reproduce: It can be reproduce on [example app](https://github.com/walterholohan/react-native-crisp-chat-sdk/tree/master/example), git clone this repo and do yarn install, yarn android

Device: Google Pixel 7a and emulator 

[chat-windows-wont-shrink.webm](https://github.com/walterholohan/react-native-crisp-chat-sdk/assets/16301430/0eac2297-d2d3-4ab9-80aa-da4c5cec16c4)

Try to add KeyboardAvoind but no luck, It seems react native have no control for this modal.
Let me know if more information is needed, Thanks.

**Comment by muhamien** [comment]
I also encountered this problem, is there a solution?

**Comment by baptistejamin** [comment]
can you try to update to the last version?

**Comment by benoitjouanigo** [comment]
I'm experiencing the same issue (Android) with the latest version of the package (0.15.2).

Has anyone found a solution?
