### ISSUE TITLE
Send message with function

### ISSUE THREAD

**Issue by stephoune** [walterholohan/react-native-crisp-chat-sdk#13]
Hi ! Thank's for your work !
I'm wondering if there is a way to send a message directly with a function without using the chat (for Android and iOS) ?

**Comment by MichaelHuy** [comment]
As I know, we can use a backend that integrates with crisp api to handle it.

**Comment by walterholohan** [comment]
@stephoune the crisp API docs can be found here https://docs.crisp.chat/api/v1/#top. Also you could post the same question on the crisp chat ios sdk repo (https://github.com/crisp-im/crisp-sdk-ios)
