### ISSUE TITLE
New architecture support

### ISSUE THREAD

**Issue by francis-switcho** [walterholohan/react-native-crisp-chat-sdk#130]
I don't see any issue/PR/commit about supporting RN's [new Architecture](https://reactnative.dev/docs/the-new-architecture/landing-page),
therefore I assume this lib is not compatible yet (I haven't looked at the code yet)
Do you have any plans regarding this?

Thank you

**Comment by baptistejamin** [comment]
The library is 100% a wrap around our native SDKs and we are not using at all  React Native rendering, so I don't think it should be a big deal
