### ISSUE TITLE
Fatal Crash on iOS

### ISSUE THREAD

**Issue by thenerdcat** [walterholohan/react-native-crisp-chat-sdk#131]
Sometimes I have been getting this when I open the app: SIGSEGV: Signal 11, Code 2 >
Attempted to dereference garbage pointer at 0x8000000000000028.

According to sentry it happens at: Crisp
+0x1c8dc4
__RawDictionaryStorage.find<T> (<compiler-generated>)

Is there any solution for this?

**Comment by baptistejamin** [comment]
Hello !

Do you still have this issue?

**Comment by paulayo93** [comment]
This is on IOS
