### ISSUE TITLE
Bump crisp-sdk android version

### ISSUE THREAD

**Issue by dutrasr** [walterholohan/react-native-crisp-chat-sdk#133]
There are some fixes deployed in the latest [@crisp-im/crisp-sdk-android](https://github.com/crisp-im/crisp-sdk-android/releases/tag/v2.0.2beta3). Is there an ETA to when this package will be updated?

**Comment by baptistejamin** [comment]
Hey!

I just did update :)

**Comment by dutrasr** [comment]
Great, thanks @baptistejamin.
