### ISSUE TITLE
Dependency Conflict with React Native 0.74.5

### ISSUE THREAD

**Issue by waelabdrabbo** [walterholohan/react-native-crisp-chat-sdk#134]
**Steps to Reproduce:**

1.  Initialize a React Native project using version 0.74.5.
2.  Run the following command to install `react-native-crisp-chat-sdk`:
    
    `npm install --save react-native-crisp-chat-sdk` 
    
3.  The installation fails with a dependency resolution error.

**Expected Behavior:** The SDK should support the latest stable version of React Native (0.74.5), allowing it to be installed without dependency conflicts.

**Actual Behavior:** The installation fails with the following error:

`npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error Found: react-native@0.74.5
npm error Could not resolve dependency: 
npm error peer react-native@"^0.73.6" from react-native-crisp-chat-sdk@0.14.4` 

**Environment:**

-   React Native Version: 0.74.5
-   `react-native-crisp-chat-sdk` Version: 0.14.4

**Comment by anasbadrusalam** [comment]
Same here

**Comment by baptistejamin** [comment]
Issue should be fixed with our latest release
