### ISSUE TITLE
Fatal Crash  on android devices

### ISSUE THREAD

**Issue by nivyamathew** [walterholohan/react-native-crisp-chat-sdk#135]
We are encountering an issue with the React Native Crisp Chat SDK, causing our app to crash on Android devices. We are using the React Native Crisp Chat SDK version 0.13.4 with React Native version 0.70.6.

The error log we received is as follow:

"java.util.UnknownFormatConversionException: Conversion = ' ' "

**Comment by baptistejamin** [comment]
Hello!

We did several updates on the package since, I would recommend to update to latest version to avoid any crash :)
