### ISSUE TITLE
Expo Plugin Uses Outdated Version of Crisp SDK

### ISSUE THREAD

**Issue by Cypherball** [walterholohan/react-native-crisp-chat-sdk#138]
### Issue Title
Expo Plugin Uses Outdated Version of Crisp SDK

### Issue Description
The Expo plugin in the file `plugin/src/withCrispChat.ts` uses an outdated version of the Crisp SDK (`2.0.0beta1`). It is not in sync with the latest releases of the Crisp SDK.

#### File Reference
- [plugin/src/withCrispChat.ts](https://github.com/walterholohan/react-native-crisp-chat-sdk/blob/c835e922bf21b42356bffe6b356995645d4342fd/plugin/src/withCrispChat.ts)

#### Current Version Used
- Crisp SDK: `2.0.0beta1`

#### Latest Release
- [Release 0.14.4](https://github.com/walterholohan/react-native-crisp-chat-sdk/releases/tag/v0.14.4) [2024-09-05] `2.0.2beta3`

### Suggested Action
Update the Crisp SDK version used in the Expo plugin to the latest available release. This will ensure compatibility and access to the latest features and fixes provided by the Crisp SDK.

### Steps to Reproduce
1. Review the file `plugin/src/withCrispChat.ts`.
2. Observe the Crisp SDK version being used (`2.0.0beta1`).

### Expected Behavior
The Expo plugin should use the latest version of the Crisp SDK.

### Actual Behavior
The Expo plugin uses an outdated version of the Crisp SDK (`2.0.0beta1`).

**Comment by baptistejamin** [comment]
Hello!

I just released a new version based on your suggestion :)
