### ISSUE TITLE
Pod install error

### ISSUE THREAD

**Issue by WesleyFaveri** [walterholohan/react-native-crisp-chat-sdk#15]
I'm trying install package but when i try to install pods i just get this error msg:
`CocoaPods could not find compatible versions for pod "react-native-crisp-chat-sdk"`

I already tried version 4.0.0 and 5.0.0

**Comment by walterholohan** [comment]
@WesleyFaveri is this still an issue for you?

**Comment by WesleyFaveri** [comment]
Not really

**Comment by harshps08** [comment]
> I'm trying install package but when i try to install pods i just get this error msg: `CocoaPods could not find compatible versions for pod "react-native-crisp-chat-sdk"`
> 
> I already tried version 4.0.0 and 5.0.0

How did you resolve this error ?
