### ISSUE TITLE
Callback when the user closes the modal

### ISSUE THREAD

**Issue by minuitagency** [walterholohan/react-native-crisp-chat-sdk#17]
Hey, 

Thanks for the update, the SDK works great on our side now, 

One quick question: how do you know the modal was closed to update the showChat state? 

Thanks, 

Théo

**Comment by predescu** [comment]
Like a workaround, I think you can use something like this:
```
setShowChat(true);
setTimeout(() => {
    setShowChat(false);
}, 1000);
```
