### ISSUE TITLE
method configure in class Crisp cannot be applied to given types;

### ISSUE THREAD

**Issue by mohamedabady** [walterholohan/react-native-crisp-chat-sdk#18]
while trying to build the app 

got this error :

error: method configure in class Crisp cannot be applied to given types;
                Crisp.configure("MY_WEBSITE_ID");
                     ^
  required: Context,String
  found: String
  reason: actual and formal argument lists differ in length

**Comment by aseferov** [comment]
It should be   Crisp.configure(getApplicationContext(), "YOUR_WEBSITE_ID");

**Comment by walterholohan** [comment]
Thanks @aseferov. Ive just pushed an update to the README to reflect this
