### ISSUE TITLE
ambiguous use of push session event

### ISSUE THREAD

**Issue by mohamedabady** [walterholohan/react-native-crisp-chat-sdk#20]
can you elaborate more on this function

**Comment by luke-lewandowski** [comment]
@mohamedabady - I would recommend reading Crisp's documentation on their capabilities. Session event gives you ability to save against the user's profile various events that might be of interest to the customer service (admin) operating Crisp/helping user.

eg. user has logged in, purchased, changed their password etc.

https://help.crisp.chat/en/article/how-can-i-push-user-events-pxu9vm/
