### ISSUE TITLE
Chatbox language is always English

### ISSUE THREAD

**Issue by Yhnlvy** [walterholohan/react-native-crisp-chat-sdk#21]
Hi there!

First of all, thank you very much for the great work :)

I have an issue with the "example" project : the chatbox language is **always** English.

Please find hereafter the context to reproduce it: 
- _Chatbox language_ : forced to be French (auto-detect disabled) from my crisp dashboard
- _iPhone / iOS simulator (v14.4)_ : French region + French language
- _react-native-crisp-chat-sdk_ : v0.6.0
- _Cocoapods_ : 1.10.1
- _Xcode_ : 12.4
- _yarn_ : 1.22.10

Nonetheless, when I run the example from the library on iOS simulator or a real device, the displayed language is still English. The same issue happens if the chatbox language detection is automatic.

Any clue?

Thanks for your help!

**Comment by minuitagency** [comment]
Hey, same issue, would be super helpful to be able to change the language! Thanks

**Comment by walterholohan** [comment]
Hi guys,

Ive just left a message on the Crisp iOS SDK github page to see if this is possible to do. Hopefully we can resolve it soon. 

Ill also investigate if there is a flag in info.plist that you can set in order to set the default language of the app.

**Comment by Yhnlvy** [comment]
> Hi guys,
> 
> Ive just left a message on the Crisp iOS SDK github page to see if this is possible to do. Hopefully we can resolve it soon.
> 
> Ill also investigate if there is a flag in info.plist that you can set in order to set the default language of the app.

Hi @walterholohan, and thanks for the quick reply.

Fun fact: I already asked an engineer of the Crisp iOS SDK team to investigate the issue and it appears that their standalone SDK (_v1.0.12_) has the expected behavior. Crisp suggested to open an issue here :)

At some point, during the setup of your example project, I ran a `pod update && pod install` that I had to revert afterwards cause it was breaking the build. After that, your library was actually loading the French translations... but I could not figure out what was the fix. So first guess, it might probably be caused by a pod side effect. Screenshot of the "mysterious" success.

<img width="333" alt="Capture d’écran 2021-03-19 à 11 58 29" src="https://user-images.githubusercontent.com/16919822/111770369-9e80ef80-88aa-11eb-9893-f265d98e4701.png">

Hope this helps!

**Comment by Yhnlvy** [comment]
Using the following code snippet in `App.tsx`
<img width="668" alt="Capture d’écran 2021-03-19 à 13 54 59" src="https://user-images.githubusercontent.com/16919822/111783657-b82a3300-88ba-11eb-8797-ec0282d8a7de.png">

leads to the results hereafter :
<img width="771" alt="Capture d’écran 2021-03-19 à 13 53 32" src="https://user-images.githubusercontent.com/16919822/111783765-d7c15b80-88ba-11eb-9601-2b14c15b0ae8.png">

As you can see, the locale gets changed on the fly from 'fr_FR' to 'en_US'.

**Comment by FRizzonelli** [comment]
@Yhnlvy Mmm that seems to doesn't work. I've tested with iOS simulator: Either I choose italian or english, chat sdk ui is always in English. Also the user is identified as "english" user, on the web sdk the parameter is exposed, I'd like to have the same here!

**Comment by Yhnlvy** [comment]
Hi @walterholohan ! Hope you're doing well :)
Did you have the chance to further investigate our issue?
Thanks!

**Comment by Elpayet** [comment]
Hello, I am also interested in this feature. That would be great.

**Comment by walterholohan** [comment]
Hey @Elpayet @Yhnlvy ill try to take a look at it over the next few days. Im fairly busy at the moment with a new baby just arriving in the family, but will try squeeze some time out to investigate this issue.

**Comment by walterholohan** [comment]
Hey @Elpayet @Yhnlvy did you try this on a real device? Ive just been trying to debug on a simulator and it seems that the locale of the simulator always returns `en_US`. Can you add the below line to your appDelegate and see what locale it returns for your device. This will help to debug this issue easier.
```
 NSLog(@"localeIdentifier: %@", [[NSLocale currentLocale] localeIdentifier]);
```

**Comment by Elpayet** [comment]
@walterholohan here is my locale on my real device :

![Capture d’écran 2021-12-03 à 16 10 51](https://user-images.githubusercontent.com/4669577/144625622-c1d053cf-360f-4333-b819-6347f17b0b50.png)

**Comment by ElpayetSupervan** [comment]
@walterholohan I've contacted Crisp. They propose this change (without any instruction or any clue to where this is going). Does it sound any bell to you ?
![image](https://user-images.githubusercontent.com/75784242/144631440-00cb05b5-bc2f-46e3-ac20-b41077f47108.png)

**Comment by ElpayetSupervan** [comment]
I couldn't be able to run the projet and test it.

**Comment by therunbuddy** [comment]
In `AppDelegate.m` in your project can you try do something like:

```
[CrispSDK configureWithWebsiteID:@"YOUR_WEBSITE_ID"];
NSLocale *frLocale = [[NSLocale alloc] initWithLocaleIdentifier:@"en_FR"];
[CrispSDK setLocale:frLocale];
  ```
  
 My obj-c is very rusty so it might not work

**Comment by Elpayet** [comment]
@therunbuddy thanks for your suggestion, unfortunately, no matter what variation of 'fr-fr' (fr_FR, fr, FR, etc...) I use, it still is in english.

@walterholohan @Yhnlvy reverting back to default initialization of Crisp, I managed to change my current locale to fr_FR, using a dummy Localizable.string file and adding support for French language in Xcode project setting.
You were right @walterholohan : the locale auto detection works, the only condition is to make sure your currentLocal is properly set, as I describe. Maybe this could be a good tip to add in this repo documentation.

**Comment by Elpayet** [comment]
Here is the result : 

![IMG_268C9EAB5595-1](https://user-images.githubusercontent.com/4669577/145021432-e4e48a59-d897-4afb-9d9a-fca7a25e3d17.jpeg)

Now it coud be interesting to override this behavior from RN based on user in-app preferences, or hard-coded arbitrary decision. what do you think ?

**Comment by walterholohan** [comment]
@Elpayet thank you for solving this issue. Would you be able to raise a PR with the suggested changes to README? I will review and then release a new version.

**Comment by Elpayet** [comment]
@walterholohan please check https://github.com/walterholohan/react-native-crisp-chat-sdk/pull/50. Thanks for your help.
