### ISSUE TITLE
Bigger "Close Chat" button

### ISSUE THREAD

**Issue by iamchriswick** [walterholohan/react-native-crisp-chat-sdk#32]
From a UX/UI point of view I think the close chat button (x) in the upper right need to be way bigger. 

There are design guidelines on how large thees buttons should be:
- iOS: https://developer.apple.com/design/human-interface-guidelines/ios/controls/buttons/
- Android: https://material.io/components/buttons#usage

**Comment by walterholohan** [comment]
Hi @iamchriswick , this library just bridges over to the official SDK's from Crisp. Would you be able to raise this issue on their repos?

iOS - https://github.com/crisp-im/crisp-sdk-ios
Android - https://github.com/crisp-im/crisp-sdk-android
