### ISSUE TITLE
ios OS versions below 14 can not open crisp chat box

### ISSUE THREAD

**Issue by mohamedabady** [walterholohan/react-native-crisp-chat-sdk#33]
when trying to call `CrispChatSDK.show()` on an ios device with OS version below 14, nothing happens. i don't get any errors

**Comment by Sherby1988** [comment]
This also happens to me. If I use iOS 13 nothing shows up. On iOS14 it shows up with no issues

**Comment by walterholohan** [comment]
Can you try again, I have just released a new version that uses the latest Crisp iOS SDK
