### ISSUE TITLE
Android resource linking failed

### ISSUE THREAD

**Issue by CMonjo** [walterholohan/react-native-crisp-chat-sdk#35]
Hi !

First, thank you for this repository, very nice !

I'm trying to configure Crisp on an RN Android app but when I want to compile I have this error:

<img width="1290" alt="Screenshot 2021-06-27 at 12 40 01" src="https://user-images.githubusercontent.com/31744890/123541416-cce15700-d744-11eb-8f92-7a2048d16822.png">

My root build.gradle

```
buildscript {
    ext {
        buildToolsVersion = "29.0.2"
        minSdkVersion = 19
        compileSdkVersion = 29
        targetSdkVersion = 29
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.5.3")
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
```

My app/build.gradle

```
android {
   ...
    defaultConfig {
        ...
        multiDexEnabled true
    }
}

dependencies {
   ...
    implementation 'im.crisp:crisp-sdk:1.0.6'
    implementation 'androidx.multidex:multidex:2.0.1'
}
```

I'm still new to RN and I must be missing something ... Thank you very much in advance !!

**Comment by walterholohan** [comment]
Can you try again, I have just release a new version that uses the latest Android SDK from Crisp
