### ISSUE TITLE
cannot close chat on android

### ISSUE THREAD

**Issue by Sherby1988** [walterholohan/react-native-crisp-chat-sdk#43]
I have implemented Crisp chat  with a boolean condition for rendering on an existing page:
I have this function 
`const openChat = () => {
        setTokenId(authStore.getSetting('crisp_code'));
        // Set user's info
        setUserEmail(8888);
        setUserNickname(authStore.user.name);
        setUserPhone(authStore.user.phone);

        // resetSession()
        setShowChat(true)
        show()
    }`

I press a button and the chat comes up normally:
on iOS when I close the chat it works ok and the app goes back to normal.
on android when I close the chat the loading screen does not disappear.
![image](https://user-images.githubusercontent.com/24829489/137338019-f0f33642-dde3-4eaf-a199-686f9583073a.png)

If I'm not mistaking this didn't happen on earlier versions.

**Comment by akinlekan28** [comment]
Facing this same issue too

**Comment by JusTmaino** [comment]
any solutions for this problem ? im using v0.10.2

**Comment by baptistejamin** [comment]
You are all using a NavigationContainer ?

**Comment by akinlekan28** [comment]
Yes, as far as it's React Navigation the NavigationContainer is needed to wrap the screens

**Comment by JusTmaino** [comment]
> You are all using a NavigationContainer ?

yes

**Comment by oliuradu** [comment]
same here..
