### ISSUE TITLE
Android: build issue

### ISSUE THREAD

**Issue by mlecoq** [walterholohan/react-native-crisp-chat-sdk#47]
Here is the logs I have when I want to build my app since today 

```
* What went wrong:
Execution failed for task ':react-native-crisp-chat-sdk:androidDependencies'.
> Could not resolve all artifacts for configuration ':react-native-crisp-chat-sdk:debugRuntimeClasspath'.
   > Could not resolve com.facebook.react:react-native:+.
     Required by:
         project :react-native-crisp-chat-sdk
      > Failed to list versions for com.facebook.react:react-native.
         > Unable to load Maven meta-data from https://dl.bintray.com/crispim/crisp-maven/com/facebook/react/react-native/maven-metadata.xml.
            > Could not get resource 'https://dl.bintray.com/crispim/crisp-maven/com/facebook/react/react-native/maven-metadata.xml'.
               > Could not GET 'https://dl.bintray.com/crispim/crisp-maven/com/facebook/react/react-native/maven-metadata.xml'. Received status code 502 from server: Bad Gateway

```

**Comment by moxspoy** [comment]
hallo! currently the bintray is down. there is not related with react native crisp chat. thank you

**Comment by amjadislam** [comment]
I'm facing the same issue since Friday. I'm not able to generate android build.

**Comment by Pandazaur** [comment]
https://status.bintray.com/incidents/d0yvk95zh58j

**Comment by mahadevRtistiq** [comment]
I have also the same issue from Friday...


* What went wrong:
Execution failed for task ':react-native-crisp-chat-sdk:mergeReleaseResources'.
> Could not resolve all files for configuration ':react-native-crisp-chat-sdk:releaseRuntimeClasspath'.
   > Could not resolve com.facebook.react:react-native:+.
     Required by:
         project :react-native-crisp-chat-sdk
      > Failed to list versions for com.facebook.react:react-native.
         > Unable to load Maven meta-data from https://dl.bintray.com/crispim/crisp-maven/com/facebook/react/react-native/maven-metadata.xml.
            > Could not get resource 'https://dl.bintray.com/crispim/crisp-maven/com/facebook/react/react-native/maven-metadata.xml'.
               > Could not GET 'https://dl.bintray.com/crispim/crisp-maven/com/facebook/react/react-native/maven-metadata.xml'. Received status code 502 from server: Bad Gateway

**Comment by jdponomarev** [comment]
same for me, still down

**Comment by abolfazlyounesi** [comment]
same error here
Could not resolve all artifacts for configuration ':react-native-crisp-chat-sdk:releaseRuntimeClasspath'.

**Comment by mlecoq** [comment]
@jdponomarev @abolfazlyounesi could you provide a small example to reproduce ?
