### ISSUE TITLE
assembleRelease issue

### ISSUE THREAD

**Issue by mahadevRtistiq** [walterholohan/react-native-crisp-chat-sdk#48]
* What went wrong:
Execution failed for task ':react-native-crisp-chat-sdk:mergeReleaseResources'.
> Could not resolve all files for configuration ':react-native-crisp-chat-sdk:releaseRuntimeClasspath'.
   > Could not resolve com.facebook.react:react-native:+.
     Required by:
         project :react-native-crisp-chat-sdk
      > Failed to list versions for com.facebook.react:react-native.
         > Unable to load Maven meta-data from https://dl.bintray.com/crispim/crisp-maven/com/facebook/react/react-native/maven-metadata.xml.
            > Could not get resource 'https://dl.bintray.com/crispim/crisp-maven/com/facebook/react/react-native/maven-metadata.xml'.
               > Could not GET 'https://dl.bintray.com/crispim/crisp-maven/com/facebook/react/react-native/maven-metadata.xml'. Received status code 502 from server: Bad Gateway

**Comment by manhhavu** [comment]
We are having the same issue, unfortunately.  At first, it was intermittent, and now it becomes blocking.

**Comment by walterholohan** [comment]
Thanks everyone, I just released a new version - https://github.com/walterholohan/react-native-crisp-chat-sdk/releases/tag/v0.9.1

**Comment by mahadevRtistiq** [comment]
thanks @mlecoq its done in new release version 0.9.1 I also added mavenCentral() in android/build.gradle.
