### ISSUE TITLE
Does it work on Expo.dev?

### ISSUE THREAD

**Issue by mateusw3c** [walterholohan/react-native-crisp-chat-sdk#52]
Recently, I needed to use Crisp inside an application with Expo. I tried using this library, but it didn't work. Is there a specific walkthrough for apps that use expo?

Ps: I use expo SDK 41.

Expo Doc: https://docs.expo.dev/versions/v41.0.0

**Comment by mlecoq** [comment]
I have made a PR to support custom dev client : https://github.com/walterholohan/react-native-crisp-chat-sdk/pull/76

**Comment by walterholohan** [comment]
@mateusw3c I just release version 0.11.0 which includes expo support. Thank you @mlecoq
