### ISSUE TITLE
Request: Version Bump to iOS SDK 1.3.0

### ISSUE THREAD

**Issue by ZComwiz** [walterholohan/react-native-crisp-chat-sdk#61]
Hi @walterholohan — can we do a version bump on[ iOS to 1.3.0](https://github.com/crisp-im/crisp-sdk-ios/releases/tag/1.3.0)?

**Comment by walterholohan** [comment]
Hi @ZComwiz , I just release 0.10.1 which bumps crisp ios sdk to 1.3.0

**Comment by ZComwiz** [comment]
@walterholohan looks like there was a bug which was patched in 1.3.1: https://github.com/crisp-im/crisp-sdk-ios/issues/66

**Comment by walterholohan** [comment]
@ZComwiz 0.10.2 released with has 1.3.1
