### ISSUE TITLE
Failing build on iOS: Multiple commands produce

### ISSUE THREAD

**Issue by patricklouipedro** [walterholohan/react-native-crisp-chat-sdk#7]
Hi,

I am trying to make the package work. After installing the package the build for iOS started failing and I am getting the error stated below. Though when I remove the package, it successfully builds again.

Anyone else encountered this before?

```
Multiple commands produce '/Library/Developer/Xcode/DerivedData/<project_name>-<omitted>/Build/Products/Debug-iphoneos/cocoapods-artifacts-Debug.txt':

1) That command depends on command in Target '<project_name>' (project '<project_name>'): script phase “[CP] Prepare Artifacts”
2) That command depends on command in Target '<project_name>' (project '<project_name>'): script phase “[CP] Prepare Artifacts”
```

I'm using RN 0.62.2

Thanks!

**Comment by walterholohan** [comment]
What version of cocoapods, xcode are you using?

**Comment by patricklouipedro** [comment]
> What version of cocoapods, xcode are you using?

Hi! I'm using cocoapods 1.9.1 and Xcode v11.4.1

**Comment by patricklouipedro** [comment]
> Try this Its Working :
> 
> In Xcode, go to File->Project/Workspace settings.
> 
> Change the build system to Legacy Build system

Hi! Thanks for the suggestion but I already tried doing this and encountered another error instead. 😞 

<img width="243" alt="Screen Shot 2020-09-07 at 10 18 39 AM" src="https://user-images.githubusercontent.com/10890275/92342496-983bda80-f0f3-11ea-8085-f02db6b691bf.png">

**Comment by walterholohan** [comment]
did you try to delete your pods and install again? e.g. `rm -rf ios/pods && cd ios && pod install`

What does your podfile look like?

**Comment by walterholohan** [comment]
Ive just released a new version of this library that updates both iOS and Android SDK's

**Comment by walterholohan** [comment]
@patricklouipedro can you check if this is still an issue with the latest version of this library?

**Comment by patricklouipedro** [comment]
Hi @walterholohan ,

Sorry for only being able to reply now. The feature had been backlogged and I'm not yet sure when we will be pushing through with the implementation. Though I'll try to install the library again to check if its still occurring. Will post an update asap. Thank you!
