### ISSUE TITLE
Error starting chat

### ISSUE THREAD

**Issue by kindacoder** [walterholohan/react-native-crisp-chat-sdk#77]
Having this issue when implemented library
![Screenshot_1655863180](https://user-images.githubusercontent.com/28186433/174927182-b1de0aeb-7f46-452d-981c-bacd73d83d40.png)

**Comment by walterholohan** [comment]
Have you set your YOUR_WEBSITE_ID in MainApplication.java

**Comment by kindacoder** [comment]
Yes

**Comment by harshps08** [comment]
Facing same issues in ios

**Comment by lapwil** [comment]
hum yes I'm also facing this issue on both OS too, 

I did replace the YOUR_WEBSITE_ID in both AppDelegate.m and MainApplication.java, and I can connect with that same ID on app.crisp.chat 🤔

**Comment by baptistejamin** [comment]
@kindacoder How did you solve the issue?

**Comment by ForevereBest** [comment]
How to solve this problem？

**Comment by lapwil** [comment]
If it can help some of you, I had an issue with the way we had configured CRISP, there is an allow domain option in security when you're on your service dashboard.
Since then, it works perfectly fine.
