### ISSUE TITLE
Press the system back button, it takes two times to return to the expected page, and again it cannot respond correctly, and it enters the gray page (I guess it is the loading page?)

### ISSUE THREAD

**Issue by ningtt** [walterholohan/react-native-crisp-chat-sdk#80]
Press the system back button, it takes two times to return to the expected page, and again it cannot respond correctly, and it enters the gray page (I guess it is the loading page?)

**Comment by baptistejamin** [comment]
Hello!

Would it be possible to get a screenshot of the issue?

**Comment by baptistejamin** [comment]
Are you using a NavigationContainer ?

**Comment by dutrasr** [comment]
@baptistejamin I think the video bellow display this issue. I'm currently using the NavigationContainer.
![gif](https://user-images.githubusercontent.com/4675549/189508472-ac05a7b9-6390-494e-abe8-a4d637b7babc.gif)

**Comment by dutrasr** [comment]
@baptistejamin and @ningtt, this issue seems to happen only when using the NavigationContainer. Not using it to display the chat appears to not display the empty screen on the go back action.

**Comment by dutrasr** [comment]
Sure. I will try as soon as possible.
