### ISSUE TITLE
iOS Archive error

### ISSUE THREAD

**Issue by ha1vy** [walterholohan/react-native-crisp-chat-sdk#81]
In debug mode, the SDK works fine, but on archive mode don't work.

My configs:
<img width="810" alt="Captura de Tela 2022-08-02 às 16 50 20" src="https://user-images.githubusercontent.com/2475567/182461030-3c9d126a-0ace-4a94-af8c-4d11197f46d7.png">

<img width="799" alt="Captura de Tela 2022-08-02 às 16 50 41" src="https://user-images.githubusercontent.com/2475567/182461087-bcf66de6-1c74-4ecc-b9db-91b43229ace2.png">

<img width="339" alt="Captura de Tela 2022-08-02 às 16 51 11" src="https://user-images.githubusercontent.com/2475567/182461170-8962a85e-7ff6-479a-a9fb-25286967bb8e.png">

Errors: 
<img width="224" alt="Captura de Tela 2022-08-02 às 16 51 54" src="https://user-images.githubusercontent.com/2475567/182461274-0c1be248-73a0-4f9f-ad74-bf47e0e0daa4.png">

Remember, this configuration works fine on debug mode.

**Comment by walterholohan** [comment]
@ha1vy what version of RN are you using?

**Comment by ha1vy** [comment]
Thanks for answer! 

"react": "17.0.1"
"react-native": "0.64.1"

**Comment by ha1vy** [comment]
Remember, this configuration works fine on debug mode.

<img width="930" alt="Captura de Tela 2022-08-29 às 14 43 18" src="https://user-images.githubusercontent.com/2475567/187264587-ac06beb3-cad9-46be-af70-3e4de1d03484.png">

**Comment by baptistejamin** [comment]
Hello!

Do you still have this issue?

**Comment by oneHamidreza** [comment]
i have this issue too.

**Comment by baptistejamin** [comment]
Can you try using the latest SDK version ?Sent from my iPhoneOn 31 Mar 2023, at 19:17, Wanderson Arantes ***@***.***> wrote:﻿
This issue is still open.
