### ISSUE TITLE
Android - Chat is not closing properly the first time

### ISSUE THREAD

**Issue by JusTmaino** [walterholohan/react-native-crisp-chat-sdk#82]
The Chat is opening without any problems but once i try to close it the first time, it stuck on loading "Starting chat...". 
While debugging, i don't see any errors, and i found out that if i leave the app (let it running in the background) and go back, the chat is open and i can close it without any issues. 
Sadly, i need to do those steps every time i start my app to have the chat working properly and it is frustrating.

Btw everything works fine on iOS

we are going to production this month, please i need help with this, thanks in advance

CRISP SDK : im.crisp:crisp-sdk:1.0.12
"react": "17.0.1"
"react-native": "0.64.3"

![loading](https://user-images.githubusercontent.com/23143481/182833497-d98d2a64-2eb8-46c8-badf-93faf8006213.png)

**Comment by baptistejamin** [comment]
Hello!

Would it be possible to send baptiste@crisp.chat a ZIP file of the project so we can reproduce the issue?

**Comment by akinlekan28** [comment]
@baptistejamin I can offer to send a reproducible demo because i am having the same issue as described here

**Comment by baptistejamin** [comment]
Sure! Please send a zip file to baptiste@crisp.chat with the reproduced issue

**Comment by JusTmaino** [comment]
> Hello!
> 
> Would it be possible to send [baptiste@crisp.chat](mailto:baptiste@crisp.chat) a ZIP file of the project so we can reproduce the issue?

Hello, thnx for the reply, i will send you today hoping to find a solution soon

**Comment by baptistejamin** [comment]
I didn't receive yet your file

**Comment by JusTmaino** [comment]
> I didn't receive yet your file

i just send it, sorry for the late answer, thanks for ur help ;)

**Comment by baptistejamin** [comment]
After investigating, it seems you are displaying the chat twice. I am currently checking a workaround.

**Comment by JusTmaino** [comment]
> After investigating, it seems you are displaying the chat twice. I am currently checking a workaround.

The chat display once you open the contact tab (using show() method), so i don't know how it open twice ? 

What about the behaviour that resolve the issue  => "once you open the chat, close it (it stuck at loading), then leaves the app (let it running in the background) and go back to the app, the chat is open and you can close it without any issues (after this manipulation, no problem at all, only if u close completly the app and you restart it)."

**Comment by baptistejamin** [comment]
Can you try with version 1.0.13 for the android SDK?

**Comment by JusTmaino** [comment]
> Can you try with version 1.0.13 for the android SDK?

First impression with the demo project i sent u, it works fine, i will try it in our main project and i will let you know, thanks for the fast reply ;)

**Comment by JusTmaino** [comment]
> Can you try with version 1.0.13 for the android SDK?

After testing with 1.0.13, everything seems working fine, thanks a lot for your help ;)

**Comment by ForevereBest** [comment]
How to solve this problem？

**Comment by baptistejamin** [comment]
Did you upgrade to the latest android SDK?
