### ISSUE TITLE
Error starting chat

### ISSUE THREAD

**Issue by ForevereBest** [walterholohan/react-native-crisp-chat-sdk#83]
error starting chat for android and ios，This happens occasionally. How can I solve it？

use version:
"react": "17.0.2",
"react-native": "0.68.0-rc.3",
"react-native-crisp-chat-sdk": "^0.11.0",

**Comment by baptistejamin** [comment]
Do you have the same issue with the web SDK?

**Comment by ForevereBest** [comment]
@baptistejamin Never used the web SDK，I only know that Android and ios have this problem
![image](https://user-images.githubusercontent.com/46803553/197758890-7318fbf9-875a-4673-a371-2d162625097e.png)

**Comment by baptistejamin** [comment]
Please try with the web SDK, it could be something related to your network or censorship.
--
Baptiste Jamin

**Comment by ForevereBest** [comment]
@baptistejamin Have you ever tried web sdk?

**Comment by c-delouvencourt** [comment]
Same problem for me

**Comment by baptistejamin** [comment]
Can you please contact our support from crisp.chat clement ?Sent from my iPhoneOn 7 Nov 2022, at 14:01, Clément de Louvencourt ***@***.***> wrote:﻿
Same problem for me

**Comment by c-delouvencourt** [comment]
Resolved by allowing all domain on my crisp widget

**Comment by SavageWilliam** [comment]
@c-delouvencourt  - do you mean by allowing all domains via the Cirsp dashboard? If so how do you do this?

I'm using expo

**Comment by baptistejamin** [comment]
Could you check this? https://help.crisp.chat/en/article/why-am-i-getting-an-invalid-chatbox-code-or-invalid-website-error-8j93zr/#1-1-lock-chatbox-to-domain-option

**Comment by SavageWilliam** [comment]
@baptistejamin  thanks for this - looks like I already had the lock disabled. Hmm

<img width="820" alt="image" src="https://user-images.githubusercontent.com/15717822/225346572-9a061fd6-d605-4fa8-a2a7-ce23907b99cc.png">

**Comment by michalpawlowski34** [comment]
Any updates? I get the same error on Android unfortunately not just occasionally but every time...

**Comment by michalpawlowski34** [comment]
No logs at all, just visible error.
Yes, I'm using 0.13.3 version.
