### ISSUE TITLE
Crisp Android Keyboard

### ISSUE THREAD

**Issue by khunghang16** [walterholohan/react-native-crisp-chat-sdk#9]
When keyboard show, i can't scroll converstation. 
Please help me.
React native 0.63.2
![Screenshot_1604205210](https://user-images.githubusercontent.com/27754944/97795232-449ec680-1c36-11eb-8906-729d1bb7b0ec.png)

**Comment by walterholohan** [comment]
Ive just released a new version of this library that updates both iOS and Android SDK's. Let me know if this fixes the above issue. I am now using the new Android SDK from Crisp Chat.

**Comment by walterholohan** [comment]
@khunghang16 closing this off as I have no control of the chat window. This is using crisp's android sdk. Please raise an issue here https://github.com/crisp-im/crisp-sdk-android if its still an issue for you on the latest version of this library.
